// packages/viewport-animate-example.vue/src/App.vue
<script setup lang="ts">
import { onMounted } from "vue";
import { ViewportAnimate } from "viewport-animate";
import examples from "../../common/examples.json";
import Table from "./components/Table.vue";

onMounted(() => {
  new ViewportAnimate({
    attribute: "data-va",
    observerThreshold: 0.01,
  }).init();
});
</script>

<template>
  <section
    v-for="(example, index) in examples.examples"
    :id="`example-${index+1}`"
    :key="`example-${index+1}`"
  >
    <Table :example="example" />
    <div
      class="example-target"
      :class="example.shape"
      :data-va="example.rule"
    ></div>
    <a
      class="view-next-example"
      :class="[index + 1 >= examples.examples.length && 'last']"
      :href="`#example-${
        index + 1 < examples.examples.length ? index + 2 : '1'
      }`"
      :data-va="`slideInUp +0.3s -${example.duration}`"
    >
      {{
        index + 1 == examples.examples.length ? "Back to top" : "Next example"
      }}
    </a>
  </section>
</template>

// packages/viewport-animate-example.react/src/App.tsx
import { useEffect } from "react";
import { ViewportAnimate } from 'viewport-animate'
import exampleData from "../../common/examples.json";
import Table from "./components/Table.tsx";

function App() {
  useEffect(() => {
    new ViewportAnimate({
      attribute: "data-va",
      observerThreshold: 0.01,
    }).init();
    console.log("hello")
  }, [])
  return (
    <>
      {exampleData["examples"].map((example, index, examples) => (
        <section key={`example-${index}`} id={`example-${index+1}`}>
          <Table example={example} />
          <div className={'example-target ' + example.shape } data-va={example.rule} ></div>
          <a 
            href={`#example-${index + 1 < examples.length ? index + 2 : '1'}`}
            className={'view-next-example ' + (index + 1 >= examples.length ? 'last' : '')}
            data-va={`slideInUp +0.3s -${example.duration}`}
          >{
            index + 1 == examples.length ? "Back to top" : "Next example"
          }</a>
        </section>
      ))}
    </>
  );
}

export default App;
