// packages/viewport-animate-example.vue/src/components/Row.vue
<script lang="ts" setup>

defineProps<{
  property: string;
  value: string;
  isDefault: boolean;
}>()

</script>
<template>
  <tr>
    <td class="property"> {{ property }} </td>
    <td class="value">
      {{ value }}
      <span v-if="isDefault">&nbsp;(default)</span>
    </td>
  </tr>
</template>

// examples/demo.react/src/components/Row.tsx
type Props = {
  property: string;
  value: string;
  isDefault: boolean;
};

function Row({ property, value, isDefault }: Props) {
  return (
    <tr>
      <td className="property">{property}</td>
      <td className="value">
        {value}
        {isDefault && <span> (default)</span>}
      </td>
    </tr>
  );
}

export default Row;
